/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

 /******************************************************************************
 * @file           : main.c
 * @author         : Mohamed Eldeeb
 * @brief          :Inter-Process communication in RTOS -APP2(Master/Slave)
 ******************************************************************************/


#include <stdint.h>
#include "FreeRTOS.h"
#include "FreeRTOSConfig.h"
#include "STM32F103C6_GPIO_DRIVERS.h"
#include "task.h"
#include "semphr.h"
#include "queue.h"

// Handles
TaskHandle_t vTaskMasterHandle = NULL;
TaskHandle_t vTaskSlaveHandle = NULL;
QueueHandle_t xQueueHandel = NULL;

// Prototype
void vTaskMasterHandler(void *Parameter);
void vTaskSlaveHandler(void *Parameter);

void HW_Init()
{
	// Init pin as output
	GPIO_Pin_Configure_t PIN13CFG;
	PIN13CFG.GPIO_Pin_Number = GPIO_PIN_13;
	PIN13CFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PIN13CFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOC, &PIN13CFG);
}


int main(void)
{
	RCC_GPIOC_CLOCK_EN();
	HW_Init();

	// Task Creation
	xTaskCreate(vTaskMasterHandler, "Master Handle", 128, NULL, 1, vTaskMasterHandle);
	xTaskCreate(vTaskSlaveHandler, "Slave Handle", 128, NULL, 2, vTaskSlaveHandle);

	// Queue Creation
	xQueueHandel = xQueueCreate(10,sizeof(uint8_t));

	// Scheduler Start
	vTaskStartScheduler();
    /* Loop forever */
	for(;;);
}

void vTaskMasterHandler(void *Parameter)
{
	uint8_t pvOFF = 0;
	uint8_t pvON = 1;

	// Send OFF to Queue
	xQueueSend(xQueueHandel,&pvOFF,(TickType_t)5);
	vTaskDelay(10);
	// Send ON to Queue
	xQueueSend(xQueueHandel,&pvON,(TickType_t)5);
	vTaskDelay(10);
}

void vTaskSlaveHandler(void *Parameter)
{
	uint8_t pvReceive = 0;

	if(0 == pvReceive)
	{
		MCAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, 0); // if receive OFF write low
	}
	else
	{
		MCAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, 1); // if receive ON write high
	}
	vTaskDelay(10);
}
