/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "FreeRTOS.h"
#include "FreeRTOSConfig.h"
#include "STM32F103C6_GPIO_DRIVERS.h"
#include "task.h"
#include "semphr.h"

/*  Task Handels  */
TaskHandle_t vTaskButtonHandl = NULL;
TaskHandle_t vTaskLedHandl = NULL;
SemaphoreHandle_t xSemaphore = NULL;

/*  Task Prototype  */
void vTaskButtonHandler (void *vParameters);
void vTaskLEDHandler (void *vParameters);


uint8_t Btn_current_state = 0;
uint8_t Btn_Previus_state = 0;


void HW_Config()
{
	/* init led pin as output */
	GPIO_Pin_Configure_t PIN13CFG;
	PIN13CFG.GPIO_Pin_Number = GPIO_PIN_13;
	PIN13CFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PIN13CFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA, &PIN13CFG);


	/* init Button pin as input */
	GPIO_Pin_Configure_t PIN15CFG;
	PIN15CFG.GPIO_Pin_Number = GPIO_PIN_15;
	PIN15CFG.GPIO_MODE = GPIO_MODE_INPUT_PD;
	MCAL_GPIO_Init(GPIOA, &PIN15CFG);

}

int main(void)
{
	RCC_GPIOA_CLOCK_EN();
	HW_Config();

	/* task creation */
	xTaskCreate(vTaskButtonHandler, "Button", 128, NULL, 1, vTaskButtonHandl);
	xTaskCreate(vTaskLEDHandler, "LED", 128, NULL, 2, vTaskLedHandl);
	//Semaphore Create
	xSemaphore = xSemaphoreCreateBinary();

	/* start kernal */
	vTaskStartScheduler();
    /* Loop forever */
	for(;;);
}


void vTaskButtonHandler (void *vParameters)
{
	for(;;)
	{
		Btn_current_state = MCAL_GPIO_Read_Pin(GPIOC, GPIO_PIN_15);
		/* this task will give semaphore when happen change in Button state */
		if(Btn_current_state != Btn_Previus_state)
		{
			xSemaphoreGive(xSemaphore);
		}

		Btn_Previus_state = Btn_current_state ;

		vTaskDelay(25);
	}
}

/* check for change happend to make corresponding action */
void vTaskLEDHandler (void *vParameters)
{
	for(;;)
	{

		/* (TickType_t) 5 ==>  if can take semaphore in time less than 5 ticks
		 * this condition will be true , else false */

		if(xSemaphoreTake( xSemaphore, (TickType_t) 5)==pdTRUE)
		{
			/* will check for change happend , when the Button Pressed Led will be ON */
			if(Btn_current_state == 1)
			{
				MCAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_LOGIC_HIGH);
			}
			else
			{
				MCAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_LOGIC_LOW);
			}
		}
		vTaskDelay(30);
	}
}
